export const UI_LANGUAGE_STORAGE_KEY = "birgus-ui-language";

export const UI_LANGUAGES = ["it", "en"] as const;
export type UiLanguage = (typeof UI_LANGUAGES)[number];

const messages: Record<string, Record<UiLanguage, string>> = {
  "language.italian": { it: "Italiano", en: "Italian" },
  "language.english": { it: "Inglese", en: "English" },
  "language.switch": { it: "Lingua interfaccia", en: "Interface language" },
  "nav.projects": { it: "Progetti", en: "Projects" },
  "nav.clients": { it: "Clienti", en: "Clients" },
  "nav.shipments": { it: "Spedizioni", en: "Shipments" },
  "nav.customerMap": { it: "Mappa clienti", en: "Customer map" },
  "nav.offerPriority": { it: "Priorita offerte", en: "Offer priorities" },
  "nav.maintenanceProposals": { it: "Proposte manutenzione", en: "Maintenance proposals" },
  "nav.maintenanceCalendar": { it: "Calendario manutenzioni", en: "Maintenance calendar" },
  "nav.workflows": { it: "Workflow", en: "Workflows" },
  "nav.archive": { it: "Archivio", en: "Archive" },
  "nav.settings": { it: "Impostazioni", en: "Settings" },
  "nav.exit": { it: "Esci", en: "Sign out" },
  "nav.compactLogo": { it: "Logo compatto", en: "Compact logo" },
  "nav.expand": { it: "Espandi menu laterale", en: "Expand sidebar" },
  "nav.collapse": { it: "Comprimi menu laterale", en: "Collapse sidebar" },
  "nav.personalDashboard": { it: "Apri dashboard personale", en: "Open personal dashboard" },
  "notifications.title": { it: "Comunicazioni", en: "Notifications" },
  "notifications.clear": { it: "Pulisci", en: "Clear" },
  "notifications.loading": { it: "Caricamento comunicazioni...", en: "Loading notifications..." },
  "notifications.empty": { it: "Hai zero comunicazioni.", en: "You have no notifications." },
  "notifications.cleared": { it: "Notifiche eliminate.", en: "Notifications cleared." },
  "notifications.clearFailed": { it: "Cancellazione notifiche non riuscita.", en: "Unable to clear notifications." },
  "notifications.position.topLeft": { it: "Alto sinistra", en: "Top left" },
  "notifications.position.topCenter": { it: "Alto centro", en: "Top center" },
  "notifications.position.topRight": { it: "Alto destra", en: "Top right" },
  "notifications.position.bottomLeft": { it: "Basso sinistra", en: "Bottom left" },
  "notifications.position.bottomCenter": { it: "Basso centro", en: "Bottom center" },
  "notifications.position.bottomRight": { it: "Basso destra", en: "Bottom right" },
  "settings.ai.loadModels": { it: "Ricerca modelli", en: "Search models" },
  "settings.ai.modelsOne": { it: "Modello caricato: {model}", en: "Model loaded: {model}" },
  "settings.ai.modelsMany": { it: "Trovati {count} modelli.", en: "Found {count} models." },
  "settings.ai.modelsEmpty": { it: "Provider raggiunto, nessun modello elencato.", en: "Provider reached, but it returned no models." },
  "settings.ai.valid": { it: "Connessione valida. Modello: {model}", en: "Connection valid. Model: {model}" },
  "settings.ai.saved": { it: "Configurazione AI salvata.", en: "AI configuration saved." },
  "settings.ai.loadFailed": { it: "Impossibile leggere le impostazioni AI.", en: "Unable to load AI settings." },
  "settings.ai.providerFailed": { it: "La richiesta al provider IA non e riuscita.", en: "The AI provider request failed." },
  "auth.title": { it: "Accedi al project manager di FGautomazioni", en: "Sign in to the FGautomazioni project manager" },
  "auth.email": { it: "Indirizzo email", en: "Email address" },
  "auth.password": { it: "Password", en: "Password" },
  "auth.remember": { it: "Ricordami", en: "Remember me" },
  "auth.forgot": { it: "Password dimenticata?", en: "Forgot password?" },
  "auth.signIn": { it: "Accedi", en: "Sign in" },
  "auth.signingIn": { it: "Accesso...", en: "Signing in..." },
  "auth.twoFactor": { it: "Autenticazione a due fattori", en: "Two-factor authentication" },
  "auth.twoFactorSetup": { it: "Configura l'app (una sola volta)", en: "Set up your authenticator app (once)" },
  "auth.twoFactorQr": { it: "QR code autenticazione a due fattori", en: "Two-factor authentication QR code" },
  "auth.otp": { it: "Codice OTP", en: "OTP code" },
  "auth.cancel": { it: "Annulla", en: "Cancel" },
  "auth.verify": { it: "Verifica 2FA", en: "Verify 2FA" },
  "auth.verifying": { it: "Verifica...", en: "Verifying..." },
  "auth.recovery": { it: "Recupero password", en: "Password recovery" },
  "auth.accountEmail": { it: "Email account", en: "Account email" },
  "auth.sendCode": { it: "Invia codice via email", en: "Send code by email" },
  "auth.sendingCode": { it: "Invio codice...", en: "Sending code..." },
  "auth.oneTimeCode": { it: "Codice monouso", en: "One-time code" },
  "auth.newPassword": { it: "Nuova password", en: "New password" },
  "auth.confirmPassword": { it: "Conferma password", en: "Confirm password" },
  "auth.newCode": { it: "Nuovo codice", en: "New code" },
  "auth.resetPassword": { it: "Reimposta password", en: "Reset password" },
  "auth.updating": { it: "Aggiornamento...", en: "Updating..." },
  "auth.invalidCredentials": { it: "Credenziali non valide.", en: "Invalid credentials." },
  "auth.loginFailed": { it: "Accesso non riuscito.", en: "Sign-in failed." },
  "auth.loginSuccess": { it: "Accesso effettuato con successo.", en: "Signed in successfully." },
  "auth.enterAuthenticatorCode": { it: "Inserisci il codice dell'app autenticatore per completare il login.", en: "Enter the code from your authenticator app to complete sign-in." },
  "auth.otpMissing": { it: "Challenge 2FA mancante. Ripeti il login.", en: "Missing 2FA challenge. Sign in again." },
  "auth.otpInvalid": { it: "Inserisci un codice OTP valido.", en: "Enter a valid OTP code." },
  "auth.twoFactorFailed": { it: "Verifica 2FA non riuscita.", en: "2FA verification failed." },
  "auth.twoFactorSuccess": { it: "Autenticazione a due fattori completata.", en: "Two-factor authentication completed." },
  "auth.emailInvalid": { it: "Inserisci un indirizzo email valido.", en: "Enter a valid email address." },
  "auth.recoverySent": { it: "Se l'account esiste, riceverai un codice monouso via email.", en: "If the account exists, you will receive a one-time code by email." },
  "auth.resetFailed": { it: "Reset password non riuscito.", en: "Password reset failed." },
  "auth.passwordUpdated": { it: "Password aggiornata. Ora puoi accedere.", en: "Password updated. You can now sign in." },
  "settings.title": { it: "Impostazioni", en: "Settings" },
  "settings.help": { it: "Modifica le preferenze visive dell'app.", en: "Edit the visual preferences for the app." },
  "settings.subtitle": { it: "Personalizza le tue preferenze", en: "Customize your preferences" },
  "settings.palette": { it: "Palette colore", en: "Color palette" },
  "settings.notificationsPosition": { it: "Posizione notifiche", en: "Notification position" },
  "settings.ocr.title": { it: "Modulo OCR", en: "OCR module" },
  "settings.ocr.description": { it: "Abilita il lettore DDT e l'elaborazione OCR nel workspace corrente.", en: "Enable the DDT reader and OCR processing in the current workspace." },
  "settings.ocr.runtime": { it: "Disattivandolo il container OCR viene arrestato e la sua memoria viene liberata. Riattivandolo, il servizio viene avviato di nuovo.", en: "Disabling it stops the OCR container and releases its memory. Enabling it starts the service again." },
  "settings.ocr.containerStopped": { it: "Servizio OCR arrestato: memoria del container liberata.", en: "OCR service stopped: container memory released." },
  "settings.ocr.sharedRunning": { it: "OCR resta attivo perche e ancora abilitato in un altro workspace.", en: "OCR remains active because it is still enabled in another workspace." },
  "settings.ocr.containerStarted": { it: "Servizio OCR avviato.", en: "OCR service started." },
  "settings.ocr.starting": { it: "OCR in preparazione: i modelli Paddle vengono caricati in background.", en: "OCR is preparing: Paddle models are loading in the background." },
  "settings.ocr.ready": { it: "OCR pronto all'uso.", en: "OCR is ready to use." },
  "settings.ocr.readyFailed": { it: "OCR non e riuscito a caricare i modelli.", en: "OCR could not load its models." },
  "settings.ocr.readyTimeout": { it: "OCR sta impiegando piu del previsto. Puoi continuare a lavorare: lo stato verra aggiornato al prossimo controllo.", en: "OCR is taking longer than expected. You can keep working; its status will update on the next check." },
  "settings.ocr.started": { it: "Modulo OCR avviato. Usa Test OCR quando vuoi verificare che sia pronto.", en: "OCR module started. Use Test OCR whenever you want to verify that it is ready." },
  "settings.ocr.test": { it: "Test OCR", en: "Test OCR" },
  "settings.ocr.testing": { it: "Test in corso...", en: "Testing..." },
  "settings.ocr.notReady": { it: "OCR non e ancora pronto. Attendi un momento e riprova il test.", en: "OCR is not ready yet. Wait a moment and test again." },
  "settings.ocr.testDisabled": { it: "Attiva il modulo OCR prima di eseguire il test.", en: "Enable the OCR module before running the test." },
  "settings.ocr.switchHint": { it: "Attiva o arresta il servizio OCR per questo workspace.", en: "Start or stop the OCR service for this workspace." },
  "settings.ocr.toggle": { it: "Attiva o disattiva OCR", en: "Enable or disable OCR" },
  "settings.ocr.stopFailed": { it: "Modulo OCR aggiornato, ma il container non e stato arrestato. Verifica il servizio OCR lifecycle e Docker.", en: "OCR module updated, but the container was not stopped. Check the OCR lifecycle service and Docker." },
  "settings.active": { it: "Attivo", en: "Enabled" },
  "settings.inactive": { it: "Disattivo", en: "Disabled" },
  "settings.ai.title": { it: "Provider IA", en: "AI provider" },
  "settings.ai.description": { it: "Scegli il tuo provider di AI", en: "Choose your AI provider" },
  "settings.ai.model": { it: "Modello AI", en: "AI model" },
  "settings.ai.selectModel": { it: "Seleziona modello", en: "Select model" },
  "settings.ai.noModels": { it: "nessun modello disponibile", en: "no model available" },
  "settings.ai.generation": { it: "Generazione", en: "Generation" },
  "settings.ai.generationHint": { it: "Controlli validi per il server vLLM configurato.", en: "Controls supported by the configured vLLM server." },
  "settings.ai.maxOutputTokens": { it: "Max token output", en: "Max output tokens" },
  "settings.ai.contextTokenLimit": { it: "Limite token contesto", en: "Context token limit" },
  "settings.ai.contextTokenLimitHint": { it: "Riduce il prompt inviato al modello; non aumenta la finestra del server.", en: "Limits the prompt sent to the model; it does not increase the server context window." },
  "settings.ai.topP": { it: "Top-p", en: "Top-p" },
  "settings.ai.topK": { it: "Top-k", en: "Top-k" },
  "settings.ai.minP": { it: "Min-p", en: "Min-p" },
  "settings.ai.repetitionPenalty": { it: "Penalty ripetizione", en: "Repetition penalty" },
  "settings.ai.seed": { it: "Seed", en: "Seed" },
  "settings.ai.seedHint": { it: "Facoltativo: rende le risposte piu ripetibili.", en: "Optional: makes responses more repeatable." },
  "settings.vllm.runtime": { it: "Runtime vLLM", en: "vLLM runtime" },
  "settings.vllm.runtimeHint": { it: "Modifica la finestra del modello e ricrea il container IA.", en: "Changes the model window and recreates the AI container." },
  "settings.vllm.contextWindow": { it: "Finestra contesto server", en: "Server context window" },
  "settings.vllm.containerRunning": { it: "Container attivo", en: "Container running" },
  "settings.vllm.containerStopped": { it: "Container non attivo", en: "Container stopped" },
  "settings.vllm.applyRestart": { it: "Applica e riavvia", en: "Apply and restart" },
  "settings.vllm.restarting": { it: "Riavvio vLLM...", en: "Restarting vLLM..." },
  "settings.vllm.updated": { it: "Configurazione vLLM aggiornata. Il modello si sta ricaricando.", en: "vLLM configuration updated. The model is loading." },
  "settings.vllm.loadFailed": { it: "Impossibile leggere il runtime vLLM.", en: "Unable to read the vLLM runtime." },
  "settings.validate": { it: "Carica", en: "Load" },
  "settings.save": { it: "Salva", en: "Save" },
  "settings.mail.title": { it: "Provider email", en: "Email provider" },
  "settings.mail.description": { it: "Provider usato dai workflow per inviare email e allegati.", en: "Provider used by workflows to send email and attachments." },
  "common.notFound": { it: "404 - Pagina non trovata", en: "404 - Page not found" },
  "common.notFoundDescription": { it: "La pagina che stai cercando non esiste oppure non hai i permessi per visualizzarla.", en: "The page you are looking for does not exist or you do not have permission to view it." },
  "common.confirmDelete": { it: "Conferma eliminazione", en: "Confirm deletion" },
  "common.delete": { it: "Elimina", en: "Delete" },
  "common.confirmDeletePrompt": { it: "Sei sicuro di voler cancellare questo elemento?", en: "Are you sure you want to delete this item?" },
  "common.typeExactly": { it: "Digita esattamente:", en: "Type exactly:" },
  "common.confirmationText": { it: "Inserisci il testo di conferma", en: "Enter the confirmation text" },
  "common.quickHelp": { it: "Aiuto rapido", en: "Quick help" },
  "common.quickHelpPage": { it: "Aiuto rapido pagina", en: "Quick page help" },
  "common.close": { it: "Chiudi", en: "Close" },
  "common.cancel": { it: "Annulla", en: "Cancel" },
  "common.save": { it: "Salva", en: "Save" },
  "common.loading": { it: "Caricamento...", en: "Loading..." },
  "common.none": { it: "Nessuno", en: "None" },
  "workflow.noText": { it: "Nessun testo prodotto.", en: "No text produced." },
  "workflow.document": { it: "Documento", en: "Document" },
  "workflow.generatedDocument": { it: "Documento generato", en: "Generated document" },
  "workflow.download": { it: "Scarica", en: "Download" },
  "workflow.deliveryComplete": { it: "Invio completato", en: "Delivery completed" },
  "workflow.deliveryIncomplete": { it: "Invio non completato", en: "Delivery not completed" },
  "workflow.recipient": { it: "Destinatario", en: "Recipient" },
  "workflow.lastRunResult": { it: "Risultato dell'ultima esecuzione", en: "Latest run result" },
  "workflow.closeOutput": { it: "Chiudi output", en: "Close output" },
  "workflow.runToView": { it: "Esegui il workflow per visualizzare un risultato.", en: "Run the workflow to view a result." },
  "workflow.outputEmpty": { it: "Questo output non ha ricevuto alcun risultato nell'ultima esecuzione. Collega un nodo che produca testo, immagine, documento o un esito di invio, poi riesegui il workflow.", en: "This output received no result in the latest run. Connect a node that produces text, an image, a document, or a delivery status, then run the workflow again." },
  "workflow.loadingTelegram": { it: "Caricamento Telegram...", en: "Loading Telegram..." },
  "workflow.manualChatId": { it: "Chat ID manuale", en: "Manual chat ID" },
  "workflow.showRuns": { it: "Mostra esecuzioni", en: "Show runs" },
  "workflow.hideRuns": { it: "Nascondi esecuzioni", en: "Hide runs" },
  "workflow.runs": { it: "Esecuzioni", en: "Runs" },
  "workflow.run": { it: "Esecuzione", en: "Run" },
  "workflow.runOrSelect": { it: "Esegui il workflow o seleziona un'esecuzione per vedere gli output effettivi.", en: "Run the workflow or select a run to view its actual outputs." },
  "workflow.finalOutput": { it: "Output finale", en: "Final output" },
  "workflow.outputWillAppear": { it: "L'output apparira al completamento dell'esecuzione.", en: "The output will appear when the run is complete." },
  "workflow.step": { it: "Passaggio", en: "Step" },
  "workflow.noOutput": { it: "Nessun output", en: "No output" },
  "workflow.finalResult": { it: "Risultato finale", en: "Final result" },
  "workflow.noElements": { it: "Nessun elemento disponibile per questo workflow.", en: "No items are available for this workflow." },
  "workflow.selectNode": { it: "Seleziona un nodo da aggiungere al canvas.", en: "Select a node to add to the canvas." },
  "workflow.modules": { it: "Workflow moduli", en: "Module workflows" },
  "workflow.activeModules": { it: "{count} moduli attivi", en: "{count} active modules" },
  "workflow.notConfigured": { it: "Non configurato", en: "Not configured" },
  "workflow.agentCount": { it: "{count} agenti", en: "{count} agents" },
  "workflow.toolCount": { it: "{count} strumenti", en: "{count} tools" },
  "workflow.noModuleWorkflows": { it: "Nessun workflow modulo disponibile per i moduli attivi.", en: "No module workflows are available for the active modules." },
  "workflow.freeWorkflows": { it: "{count} workflow liberi", en: "{count} free workflows" },
  "workflow.new": { it: "Nuovo workflow", en: "New workflow" },
  "workflow.create": { it: "Crea workflow", en: "Create workflow" },
  "workflow.creating": { it: "Creazione...", en: "Creating..." },
  "workflow.createHint": { it: "Parte vuoto: Input e Output, senza copiare alcun flusso esistente.", en: "Starts empty: Input and Output, without copying an existing flow." },
  "workflow.name": { it: "Nome", en: "Name" },
  "workflow.back": { it: "Indietro", en: "Back" },
  "workflow.context": { it: "Contesto", en: "Context" },
  "workflow.uploadedDocuments": { it: "Documenti caricati", en: "Uploaded documents" },
  "workflow.workspaceKnowledge": { it: "Knowledge workspace", en: "Workspace knowledge" },
  "workflow.deleteSelected": { it: "Elimina selezionati", en: "Delete selected" },
  "workflow.undo": { it: "Annulla", en: "Undo" },
  "workflow.redo": { it: "Ripristina", en: "Redo" },
  "workflow.running": { it: "Esecuzione...", en: "Running..." },
  "workflow.saveAndRun": { it: "Salva ed esegui", en: "Save and run" },
  "workflow.saving": { it: "Salvataggio...", en: "Saving..." },
  "workflow.nodeCategories": { it: "Categorie nodi workflow", en: "Workflow node categories" },
  "workflow.openAllNodes": { it: "Apri tutti i nodi della categoria", en: "Open all nodes in this category" },
  "workflow.nodesAvailable": { it: "{count} nodi disponibili", en: "{count} nodes available" },
  "workflow.closeNodePicker": { it: "Chiudi selettore nodi", en: "Close node picker" },
  "workflow.searchNode": { it: "Cerca un nodo", en: "Search a node" },
  "workflow.noNodesFound": { it: "Nessun nodo trovato.", en: "No nodes found." },
  "workflow.help": { it: "Crea workflow dai moduli attivi o usa un playground libero.", en: "Create workflows from active modules or use a free playground." },
  "workflow.subtitle": { it: "Scegli un modulo o crea un workflow libero da un playground vuoto.", en: "Choose a module or create a free workflow from an empty playground." },
  "workflow.inputText": { it: "Inserisci il testo iniziale", en: "Enter the initial text" },
  "workflow.searchKnowledge": { it: "Cosa vuoi cercare?", en: "What do you want to search for?" },
  "workflow.allCategories": { it: "Tutte le categorie", en: "All categories" },
  "workflow.contract": { it: "Contratto", en: "Contract" },
  "workflow.quotation": { it: "Preventivo", en: "Quotation" },
  "workflow.other": { it: "Altro", en: "Other" },
  "workflow.documentIds": { it: "ID documenti, uno per riga", en: "Document IDs, one per line" },
  "workflow.request": { it: "Richiesta, es. riassumi i documenti", en: "Request, e.g. summarize the documents" },
  "workflow.connectedInput": { it: "Input dal nodo collegato", en: "Input from the connected node" },
  "workflow.previousOutput": { it: "Lascia vuoto per usare l'output precedente", en: "Leave empty to use the previous output" },
  "workflow.instructions": { it: "Istruzioni", en: "Instructions" },
  "workflow.requiredInstructions": { it: "Istruzioni (obbligatorie)", en: "Instructions (required)" },
  "workflow.connectedContent": { it: "Contenuto dal nodo collegato", en: "Content from the connected node" },
  "workflow.documentContent": { it: "Contenuto documento", en: "Document content" },
  "workflow.fileName": { it: "Nome file", en: "File name" },
  "workflow.connectedFileName": { it: "Nome file dal nodo collegato", en: "File name from the connected node" },
  "workflow.emailRecipient": { it: "Email destinatario", en: "Recipient email" },
  "workflow.subject": { it: "Oggetto", en: "Subject" },
  "workflow.emailBody": { it: "Corpo email", en: "Email body" },
  "workflow.message": { it: "Messaggio", en: "Message" },
  "workflow.connectContent": { it: "Collega contenuto", en: "Connect content" },
  "workflow.whatsappNumber": { it: "Numero WhatsApp, es. 393...", en: "WhatsApp number, e.g. 393..." },
  "workflow.scheduleContext": { it: "Di cosa deve parlare l'email?", en: "What should the email be about?" },
  "workflow.tone": { it: "Tono (professionale)", en: "Tone (professional)" },
  "workflow.extraInstructions": { it: "Istruzioni aggiuntive", en: "Additional instructions" },
  "workflow.mailboxHint": { it: "Controlla la casella email ed elabora gli allegati all'esecuzione del workflow.", en: "Checks the mailbox and processes attachments when the workflow runs." },
  "workflow.defaultPrompt": { it: "Prompt default", en: "Default prompt" },
  "workflow.defaultTemplate": { it: "Template di default del nodo", en: "Default node template" },
  "workflow.updateDefaultPrompt": { it: "Aggiornare il prompt default?", en: "Update the default prompt?" },
  "workflow.updateDefaultPromptHint": { it: "Cambiera il template salvato per questo nodo.", en: "This changes the saved template for this node." },
  "archive.title": { it: "Archivio", en: "Archive" },
  "archive.help": { it: "Consulta i documenti del workspace, il loro stato knowledge e gli elementi nel cestino.", en: "Browse workspace documents, their knowledge status, and items in the trash." },
  "archive.documents": { it: "Documenti", en: "Documents" },
  "archive.trash": { it: "Cestino", en: "Trash" },
  "archive.all": { it: "Tutto", en: "All" },
  "archive.modules": { it: "Moduli salvati", en: "Saved modules" },
  "archive.playgrounds": { it: "Playground", en: "Playgrounds" },
  "archive.searchDocument": { it: "Cerca documento", en: "Search documents" },
  "archive.knowledgeAll": { it: "Knowledge: tutte", en: "Knowledge: all" },
  "archive.inKnowledge": { it: "In knowledge", en: "In knowledge" },
  "archive.notInKnowledge": { it: "Non in knowledge", en: "Not in knowledge" },
  "archive.processing": { it: "In elaborazione", en: "Processing" },
  "archive.loadingDocuments": { it: "Caricamento documenti...", en: "Loading documents..." },
  "archive.noDocuments": { it: "Nessun documento in questo contenitore.", en: "No documents in this container." },
  "archive.origin": { it: "Origine", en: "Origin" },
  "archive.date": { it: "Data", en: "Date" },
  "archive.size": { it: "Dimensione", en: "Size" },
  "archive.actions": { it: "Azioni", en: "Actions" },
  "archive.workspace": { it: "Workspace", en: "Workspace" },
  "archive.moveToTrash": { it: "Sposta nel cestino", en: "Move to trash" },
  "archive.emptyTrash": { it: "Svuota cestino", en: "Empty trash" },
  "archive.loadingTrash": { it: "Caricamento archivio...", en: "Loading archive..." },
  "archive.noTrash": { it: "Nessun elemento archiviato per questo blocco.", en: "No archived items in this section." },
  "archive.type": { it: "Tipo", en: "Type" },
  "archive.item": { it: "Elemento", en: "Item" },
  "archive.project": { it: "Progetto", en: "Project" },
  "archive.details": { it: "Dettagli", en: "Details" },
  "archive.restore": { it: "Ripristina", en: "Restore" },
  "archive.deletePermanently": { it: "Elimina definitivo", en: "Delete permanently" },
  "chat.assistant": { it: "Assistente Birgus", en: "Birgus assistant" },
  "chat.new": { it: "Nuova chat", en: "New chat" },
  "chat.expand": { it: "Espandi chat", en: "Expand chat" },
  "chat.reduce": { it: "Riduci chat", en: "Reduce chat" },
  "chat.close": { it: "Chiudi chat", en: "Close chat" },
  "chat.empty": { it: "Chiedimi informazioni su progetti, documenti o storici. Puoi allegarmi documenti per analizzarli.", en: "Ask me about projects, documents, or history. You can attach documents for me to analyze." },
  "chat.processing": { it: "Elaborazione", en: "Processing" },
  "chat.message": { it: "Messaggio", en: "Message" },
  "chat.write": { it: "Scrivi una domanda...", en: "Write a question..." },
  "chat.attachDocument": { it: "Allega documento", en: "Attach document" },
  "chat.attach": { it: "Allega", en: "Attach" },
  "chat.knowledge": { it: "Conoscenza dati", en: "Data knowledge" },
  "chat.knowledgeOn": { it: "Usa anche la knowledge del workspace", en: "Also use workspace knowledge" },
  "chat.knowledgeOff": { it: "Usa solo i documenti allegati alla chat", en: "Use only documents attached to the chat" },
  "chat.send": { it: "Invia", en: "Send" },
  "chat.open": { it: "Apri assistente", en: "Open assistant" },
  "superadmin.help": { it: "Gestisci utenti, ruoli e accessi dei workspace.", en: "Manage users, roles, and workspace access." },
  "superadmin.subtitle": { it: "Utenti, ruoli e accessi sensibili cross-workspace.", en: "Users, roles, and sensitive cross-workspace access." },
  "superadmin.users": { it: "utenti", en: "users" },
  "superadmin.roles": { it: "ruoli", en: "roles" },
  "superadmin.searchUser": { it: "Cerca utente", en: "Search user" },
  "ddt.help": { it: "Carica un PDF DDT, avvia l'analisi e controlla i dati estratti.", en: "Upload a DDT PDF, run the analysis, and review the extracted data." },
  "ddt.subtitle": { it: "Analizzatore di Documenti di Trasporto", en: "Transport document analyzer" },
  "ddt.workflow": { it: "Workflow DDT", en: "DDT workflow" },
  "ddt.workflowHint": { it: "Seleziona un PDF: il modulo lo salva e avvia il workflow OCR + analisi AI.", en: "Select a PDF: the module saves it and starts the OCR and AI analysis workflow." },
  "ddt.pdf": { it: "File PDF", en: "PDF file" },
  "superadmin.workspace": { it: "workspace", en: "workspaces" },
  "superadmin.searchPlaceholder": { it: "nome, cognome o email", en: "name, surname, or email" },
  "superadmin.operatingWorkspace": { it: "Workspace operativo", en: "Operating workspace" },
  "superadmin.allWorkspaces": { it: "Tutti i workspace", en: "All workspaces" },
  "superadmin.refresh": { it: "Aggiorna", en: "Refresh" },
  "superadmin.updated": { it: "Vista aggiornata", en: "View updated" },
  "superadmin.usersTitle": { it: "Utenti", en: "Users" },
  "superadmin.selectUser": { it: "Seleziona utente", en: "Select user" },
  "superadmin.noUsers": { it: "Nessun utente trovato con i filtri attuali.", en: "No users found for the current filters." },
  "superadmin.active": { it: "Attivo", en: "Active" },
  "superadmin.inactive": { it: "Disattivo", en: "Inactive" },
  "superadmin.manage": { it: "Gestisci", en: "Manage" },
  "superadmin.createUser": { it: "Crea utente", en: "Create user" },
  "superadmin.createHint": { it: "La creazione usa il workspace operativo selezionato.", en: "Creation uses the selected operating workspace." },
  "superadmin.firstName": { it: "Nome", en: "First name" },
  "superadmin.lastName": { it: "Cognome", en: "Last name" },
  "superadmin.initialPassword": { it: "Password iniziale", en: "Initial password" },
  "superadmin.passwordHint": { it: "8 caratteri, maiuscola e numero", en: "8 characters, uppercase letter, and number" },
  "superadmin.generatePassword": { it: "Genera password", en: "Generate password" },
  "superadmin.showPassword": { it: "Mostra password", en: "Show password" },
  "superadmin.hidePassword": { it: "Nascondi password", en: "Hide password" },
  "superadmin.initialRole": { it: "Ruolo iniziale", en: "Initial role" },
  "superadmin.userManagement": { it: "Gestione utente", en: "User management" },
  "superadmin.closeUserManagement": { it: "Chiudi gestione utente", en: "Close user management" },
  "superadmin.accessSessions": { it: "Accesso e sessioni", en: "Access and sessions" },
  "superadmin.disableUser": { it: "Disattiva utente", en: "Disable user" },
  "superadmin.enableUser": { it: "Attiva utente", en: "Enable user" },
  "superadmin.revokeSessions": { it: "Revoca sessioni", en: "Revoke sessions" },
  "superadmin.resetPassword": { it: "Reset password", en: "Reset password" },
  "superadmin.forcedPassword": { it: "Nuova password forzata", en: "New forced password" },
  "superadmin.updatePassword": { it: "Aggiorna password", en: "Update password" },
  "superadmin.memberships": { it: "Membership", en: "Memberships" },
  "superadmin.noMembership": { it: "Nessuna membership trovata.", en: "No membership found." },
  "superadmin.noRole": { it: "nessun ruolo", en: "no role" },
  "superadmin.assignWorkspace": { it: "Associa a workspace", en: "Assign to workspace" },
  "superadmin.role": { it: "Ruolo", en: "Role" },
  "superadmin.assign": { it: "Associa workspace", en: "Assign workspace" },
  "superadmin.workspaceRole": { it: "Ruolo nel workspace", en: "Workspace role" },
  "superadmin.notMember": { it: "L'utente non risulta membro del workspace selezionato.", en: "The user is not a member of the selected workspace." },
  "superadmin.saveRole": { it: "Salva ruolo", en: "Save role" },
  "superadmin.moduleAccess": { it: "Accesso moduli", en: "Module access" },
  "superadmin.moduleAccessHint": { it: "ALLOW forza abilitazione utente, DENY forza disabilitazione, Clear torna allo stato workspace.", en: "ALLOW forces user enablement, DENY forces disablement, and Clear returns to the workspace setting." },
  "superadmin.module": { it: "Modulo", en: "Module" },
  "superadmin.override": { it: "Override", en: "Override" },
  "superadmin.effective": { it: "Effettivo", en: "Effective" },
  "clients.help": { it: "Cerca, modifica o crea un cliente.", en: "Search, edit, or create a customer." },
  "clients.subtitle": { it: "Anagrafica Clienti", en: "Customer directory" },
  "clients.new": { it: "Nuovo cliente", en: "New customer" },
  "clients.search": { it: "Ricerca clienti...", en: "Search customers..." },
  "projects.help": { it: "Cerca un progetto, aprilo o crea una nuova commessa.", en: "Search a project, open it, or create a new job." },
  "projects.subtitle": { it: "Seleziona un progetto per vedere i suoi versionamenti", en: "Select a project to view its versions" },
  "projects.new": { it: "Nuovo progetto", en: "New project" },
  "projects.search": { it: "Ricerca progetto...", en: "Search projects..." },
  "shipments.help": { it: "Consulta le spedizioni collegate alle versioni progetto e apri la configurazione tecnica della singola spedizione.", en: "Browse shipments linked to project versions and open the technical configuration of each shipment." },
  "shipments.subtitle": { it: "Ogni versione progetto genera una singola spedizione dedicata.", en: "Each project version produces one dedicated shipment." },
  "shipments.list": { it: "Elenco spedizioni", en: "Shipment list" },
  "shipments.search": { it: "Ricerca spedizioni...", en: "Search shipments..." },
  "shipping.help": { it: "Configura e salva i dati tecnici della spedizione collegata alla versione progetto.", en: "Configure and save technical data for the shipment linked to the project version." },
  "shipping.unassignedCustomer": { it: "Cliente non associato", en: "No customer assigned" },
  "shipping.status": { it: "Stato", en: "Status" },
  "shipping.lastSaved": { it: "Ultimo salvataggio", en: "Last saved" },
  "shipping.never": { it: "mai", en: "never" },
  "shipping.backToList": { it: "Torna alla lista", en: "Back to list" },
  "account.title": { it: "Dashboard personale", en: "Personal dashboard" },
  "account.help": { it: "Consulta le informazioni del tuo account e le impostazioni rapide.", en: "View your account information and quick settings." },
  "account.loading": { it: "Caricamento dati utente...", en: "Loading user data..." },
  "account.none": { it: "Nessuna informazione disponibile al momento.", en: "No information is currently available." },
  "account.subtitle": { it: "Area account con informazioni utili e impostazioni rapide.", en: "Account area with useful information and quick settings." },
  "account.profile": { it: "Profilo", en: "Profile" },
  "account.role": { it: "Ruolo", en: "Role" },
  "account.connectedApps": { it: "Applicativi collegabili", en: "Connectable apps" },
  "account.connectedAppsHint": { it: "Collega i canali personali usati dai workflow.", en: "Connect the personal channels used by workflows." },
  "account.app": { it: "Applicativo", en: "App" },
  "account.telegramHint": { it: "Genera un codice e invialo al bot: Birgus associa in automatico il tuo Chat ID al profilo.", en: "Generate a code and send it to the bot: Birgus automatically associates your Chat ID with your profile." },
  "account.generating": { it: "Generazione...", en: "Generating..." },
  "account.generateCode": { it: "Genera codice", en: "Generate code" },
  "account.sendWithin": { it: "Invia questo messaggio al bot entro 10 minuti.", en: "Send this message to the bot within 10 minutes." },
  "account.copyTelegram": { it: "Copia comando Telegram", en: "Copy Telegram command" },
  "account.openTelegram": { it: "Apri @{name} e collega l'account", en: "Open @{name} and connect the account" },
  "account.noApps": { it: "Nessun applicativo collegato.", en: "No connected apps." },
  "account.connected": { it: "Collegato", en: "Connected" },
  "account.toVerify": { it: "Da verificare", en: "To verify" },
  "account.remove": { it: "Rimuovi {name}", en: "Remove {name}" },
  "account.changePassword": { it: "Cambio password", en: "Change password" },
  "account.currentPassword": { it: "Password attuale", en: "Current password" },
  "account.newPassword": { it: "Nuova password", en: "New password" },
  "account.confirmNewPassword": { it: "Conferma nuova password", en: "Confirm new password" },
  "account.updating": { it: "Aggiornamento...", en: "Updating..." },
  "account.preferences": { it: "Preferenze personali", en: "Personal preferences" },
  "account.preferencesHint": { it: "Queste impostazioni valgono solo per il tuo utente nel workspace corrente.", en: "These settings apply only to your user in the current workspace." },
  "account.palette": { it: "Palette colore", en: "Color palette" },
  "account.notifications": { it: "Notifiche popup", en: "Notification popups" },
  "account.notificationsHint": { it: "Mostra le conferme e gli avvisi temporanei dell'applicazione.", en: "Show temporary confirmations and alerts from the application." },
  "account.notificationsPosition": { it: "Posizione notifiche", en: "Notification position" },
  "account.notificationsOn": { it: "Attiva o disattiva le notifiche popup", en: "Enable or disable notification popups" },
  "ai.error.network": {
    it: "Impossibile raggiungere il provider IA. Controlla Base URL: IP o nome host, porta, servizio avviato e rete Docker.",
    en: "Unable to reach the AI provider. Check the Base URL: IP address or hostname, port, running service, and Docker network.",
  },
  "ai.error.timeout": {
    it: "Il provider IA non ha risposto entro il timeout. Verifica che il modello sia avviato o aumenta il timeout.",
    en: "The AI provider did not respond before the timeout. Check that the model is running or increase the timeout.",
  },
  "ai.error.unauthorized": {
    it: "Il provider IA ha rifiutato le credenziali. Verifica la chiave API configurata.",
    en: "The AI provider rejected the credentials. Check the configured API key.",
  },
  "ai.error.forbidden": {
    it: "Il provider IA ha negato l'accesso. Verifica permessi, chiave API e policy del servizio.",
    en: "The AI provider denied access. Check permissions, API key, and service policy.",
  },
  "ai.error.endpoint": {
    it: "L'endpoint del provider non esiste. Verifica Base URL e il percorso OpenAI-compatible /v1/models.",
    en: "The provider endpoint does not exist. Check the Base URL and the OpenAI-compatible /v1/models path.",
  },
  "ai.error.invalidResponse": {
    it: "Il provider ha risposto in un formato non compatibile. Deve esporre una risposta OpenAI-compatible per /v1/models.",
    en: "The provider returned an incompatible format. It must expose an OpenAI-compatible response for /v1/models.",
  },
  "ai.error.http": {
    it: "Il provider IA ha restituito un errore del server. Verifica i log del servizio e che il modello sia disponibile.",
    en: "The AI provider returned a server error. Check the service logs and that the model is available.",
  },
};

export const isUiLanguage = (value: string | null): value is UiLanguage => UI_LANGUAGES.includes(value as UiLanguage);

export function translate(language: UiLanguage, key: string, values: Record<string, string | number> = {}): string {
  const template = messages[key]?.[language] ?? messages[key]?.it ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export function aiProviderErrorMessage(language: UiLanguage, code: string | null): string {
  switch (code) {
    case "AI_PROVIDER_NETWORK_UNREACHABLE": return translate(language, "ai.error.network");
    case "AI_PROVIDER_TIMEOUT": return translate(language, "ai.error.timeout");
    case "AI_PROVIDER_UNAUTHORIZED": return translate(language, "ai.error.unauthorized");
    case "AI_PROVIDER_FORBIDDEN": return translate(language, "ai.error.forbidden");
    case "AI_PROVIDER_ENDPOINT_NOT_FOUND": return translate(language, "ai.error.endpoint");
    case "AI_PROVIDER_INVALID_RESPONSE": return translate(language, "ai.error.invalidResponse");
    default: return translate(language, "ai.error.http");
  }
}
