export const APP_ROUTES = {
  dashboard: "/dashboard",
  personalDashboard: "/home",
  projects: "/projects",
  projectNew: "/projects/new",
  projectVersions: (id: string) => `/projects/${id}`,
  projectEdit: (id: string) => `/projects/edit/${id}`,
  clients: "/clients",
  clientNew: "/clients/new",
  clientEdit: (id: number | string) => `/clients/edit/${id}`,
  commissions: "/commesse",
  commissionRecord: (id: string) => `/commesse/${id}`,
  dataCollectionChecklists: "/checklist-raccolta-dati",
  dataCollectionChecklist: (id: string) => `/checklist-raccolta-dati/${id}`,
  ddtReader: "/ddt-reader",
  measureReport: "/measure-report",
  workflows: "/workflows",
  customerMap: "/mappa-clienti",
  offerPriority: "/priorita-offerte",
  maintenanceProposals: "/proposte-manutenzione",
  maintenanceCalendar: "/calendario-manutenzioni",
  archive: "/archivio",
  superadmin: "/superadmin",
  settings: "/settings",
  brainy: "/brainy",
  login: "/login",
} as const;
