import { DdtAnalysisInput } from "../repositories/DdtProcessingRepository.js";
import { DdtAnalyzer } from "./DdtAnalyzer.js";

export class StubDdtAnalyzer implements DdtAnalyzer {
  public async analyze(_ddtDocumentId: string): Promise<DdtAnalysisInput> {
    return {
      movementType: "sconosciuto",
      movementScope: "sconosciuto",
      mainWarehouseAction: "sconosciuto",
      bollaNumber: null,
      commessaReference: null,
      transferNote: null,
      articleCount: 0,
      warehouseDelta: 0,
      summary: "Analysis placeholder generated by stub analyzer.",
      rawResponse: {
        provider: "stub",
        note: "Replace with OCR + AI pipeline implementation.",
      },
      articleItems: [],
    };
  }
}
